// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"cloud.google.com/go/civil"
	"github.com/google/uuid"
)

type Group struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	GroupName string
}

type GroupQuestion struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	Date       civil.Date
	QuestionID uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	CreatedBy  uuid.UUID
}

type GroupResponse struct {
	ID              uuid.UUID
	GroupQuestionID uuid.UUID
	Response        string
	CreatedAt       time.Time
	AuthorID        uuid.UUID
}

type Question struct {
	ID        uuid.UUID
	Text      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Name      string
	Birthday  sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}
