// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (id, text, created_at, updated_at)
VALUES (gen_random_uuid(), $1, NOW(), NOW())
RETURNING id, text, created_at, updated_at
`

func (q *Queries) CreateQuestion(ctx context.Context, text string) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion, text)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, id)
	return err
}
